authors:
   gbvitrano:
     name: gbvitrano
     description: Autore
     avatar: https://github.com/gbvitrano.png
     url: https://twitter.com/gbvitrano
   aborruso:
     name: Andrea Borruso
     description: Autore
     avatar: https://github.com/aborruso.png
     url: https://twitter.com/aborruso
   pigreco:
     name: Totò Fiandaca
     description: Autore
     avatar: https://github.com/pigreco.png
     url: https://twitter.com/totofiandaca